### ISSUE TITLE
CUDA OOM Error on 2x upscaling

### ISSUE THREAD

**Issue by DenkingOfficial** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#10]
I tried to upscale 576*1024 image using R-ESRGAN 4x+, but it gives me an out of memory error
Log:
```torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.12 GiB (GPU 0; 8.00 GiB total capacity; 6.08 GiB already allocated; 0 bytes free; 6.17 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF```

My GPU is RTX2060 Super (8 GB VRAM), but it can't handle that
Maybe I'm doing something wrong
Settings that I used:

![image](https://user-images.githubusercontent.com/38957619/224153834-303a59da-4cb1-4b5d-850c-67dfb3b8fe7c.png)

Any help or explanation is greatly appreciated!!!

UPD: I tried with and without "Overwrite image size" checked

**Comment by DenkingOfficial** [comment]
Looks like I forgot to turn on tiled VAE setting
Or I shouldn't?

**Comment by LightChaser666** [comment]
You should definitely open Tiled VAE. That is dedicated to prevent VAE-rooted OOMs. If you succeeded, please close the issue!

**Comment by DenkingOfficial** [comment]
> You should definitely enable Tiled VAE. That is dedicated to prevent VAE-rooted OOMs. By the way, I have updated some minor fix about image colors (as well as quality). If you succeeded, please close the issue!

Yes, it is working now
But details are not so good as written in the README

**Comment by LightChaser666** [comment]
There is another issue discussing the topic. You can refer to that on how to get finer details by reproducing my params.
