### ISSUE TITLE
HIP out of memory on wide pictures.

### ISSUE THREAD

**Issue by 49RpK5dY** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#53]
I'm trying to 2x upscale a 896x384 picture. It used to work with Encoder Tile Size 1024, Decoder Tile Size 64. Since [remove bbox limit and add tips](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/commit/a6bc846ecabacf6d19bc05529f9d6f798d2f9733) I can only use Encoder Tile Size 768. And on the latest [fix neg prompt errors](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/commit/058013db80bdaafdcfa28b62c1f5e228831c2211) commit it doesn't work at all even with the lowest Encoder Tile Size 256.
Upscaling a 512x768 and 768x512 pictures still works with Encoder Tile Size 1024. Changing latent tile size doesn't help as well.
I'm using AMD RX 5700 with 8GB vram. Launching in docker with `--no-half --medvram --no-half-vae`.

Here's an error code:
```
[Tiled Diffusion] upscaling image with 4x_NMKD-Superscale-SP_178000_G...
[Tiled VAE]: input_size: torch.Size([1, 3, 768, 1792]), tile_size: 256, padding: 32
[Tiled VAE]: split to 3x7 = 21 tiles. Optimal tile size 256x256, original tile size 256x256
[Tiled VAE]: Executing Encoder Task Queue: 100%|███████████████████████████████| 1911/1911 [00:05<00:00, 339.96it/s]
[Tiled VAE]: Done in 5.831s, max VRAM alloc 611.158 MB
  0%|                                                                                        | 0/20 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(lxdnubrzsapm7fm)', 0, 'crow', '(deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, (mutated hands and fingers:1.4), disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, (poorly drawn eyes, deformed iris and pupils:1.1), (anime, painting, 3d render:1.1), (ugly eyes and mouth, missing teeth:1.2)', ['upscale'], <PIL.Image.Image image mode=RGBA size=896x384 at 0x7FFA0844A040>, None, None, None, None, None, None, 20, 5, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.4, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 1, 32, 0, 'outputs/txt2img', '', '', [], 0, True, 'Mixture of Diffusers', False, True, 1024, 1024, 64, 96, 16, 1, '4x_NMKD-Superscale-SP_178000_G', 2, False, False, 1, False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', False, 1, 0.4, 0.4, 0.2, 0.2, '', '', True, True, True, False, 0, 256, 64, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 128, 64, 0.35, 128, 5, True, 0, False, 8, 0, 2, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "/sd/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/sd/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/sd/modules/img2img.py", line 171, in img2img
    processed = process_images(p)
  File "/sd/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/sd/modules/processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/sd/modules/processing.py", line 1054, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "/sd/modules/sd_samplers_kdiffusion.py", line 324, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/sd/modules/sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "/sd/modules/sd_samplers_kdiffusion.py", line 324, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/sd/venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/sd/repositories/k-diffusion/k_diffusion/sampling.py", line 553, in sample_dpmpp_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/modules/sd_samplers_kdiffusion.py", line 138, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": c_crossattn, "c_concat": [image_cond_in[a:b]]})
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/sd/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/sd/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/sd/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 776, in forward
    h = module(h, emb, context)
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 324, in forward
    x = block(x, context=context[i])
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 259, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py", line 129, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 262, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/modules/sd_hijack_optimizations.py", line 129, in split_cross_attention_forward
    s2 = s1.softmax(dim=-1, dtype=q.dtype)
torch.cuda.OutOfMemoryError: HIP out of memory. Tried to allocate 1.72 GiB (GPU 0; 7.98 GiB total capacity; 5.18 GiB already allocated; 1018.00 MiB free; 6.93 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_HIP_ALLOC_CONF
```

**Comment by pkuliyi2015** [comment]
There is a GPU leakage. I'm detecting the cause and will fix this rapidly.

**Comment by sealclubber** [comment]
> There is a GPU leakage. I'm detecting the cause and will fix this rapidly.

To prevent opening multiple issues I'm curious if my issue is related. I'm getting 

`RuntimeError: Not enough memory, use lower resolution (max approx. 2368x2368). Need: 23.5GB free, Have:18.9GB free`

after updating to the latest commit. I was able to generate images at 4k fine until I updated... if this isn't related I can cobble together whatever logs you need.

Thanks

**Comment by 49RpK5dY** [comment]
@pkuliyi2015 Thanks. Much appreciated. On other note, vae_optimize.py doesn't seem to reed parameters from ui-config.json. Is there a way to force it to read `Encoder Tile Size/value` and `Decoder Tile Size/value` from config instead of calculating recommended by the script, since it needs more memory on AMD?

**Comment by 49RpK5dY** [comment]
That's great news. Thanks.

**Comment by pkuliyi2015** [comment]
Leakage fixed, please have a test.

**Comment by sealclubber** [comment]
@pkuliyi2015 This commit isn't working for me, still getting a runtime error complaining about memory on a 3090 while making a 4k image, which only cropped up in the past couple commits. Should I open a new request or post the logs here?

**Comment by pkuliyi2015** [comment]
Just here. I can see it.

**Comment by sealclubber** [comment]
Here's the output, let me know if you need anything else or have more questions:

`[Tiled Diffusion] upscaling image with Nearest...
[Tiled VAE]: input_size: torch.Size([1, 3, 2160, 3840]), tile_size: 1024, padding: 32
[Tiled VAE]: split to 3x4 = 12 tiles. Optimal tile size 960x704, original tile size 1024x1024
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 1024 x 576 image
[Tiled VAE]: Executing Encoder Task Queue: 100%|██████████| 1092/1092 [00:01<00:00, 922.95it/s] 
[Tiled VAE]: Done in 1.564s, max VRAM alloc 3135.711 MB
  0%|          | 0/13 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(belc93llt06e0qk)', 0, 'best quality, masterpiece, absurdres, high detail', 'easynegative', [], <PIL.Image.Image image mode=RGBA size=1816x1024 at 0x7F903D355330>, None, None, None, None, None, None, 35, 15, 4, 0, 1, False, False, 1, 1, 9, 1.5, 0.35, -1.0, -1.0, 0, 0, 0, False, 540, 960, 0, 0, 32, 0, '', '', '', [], 0, True, 'MultiDiffusion', False, False, 1024, 1024, 128, 128, 36, 4, 'Nearest', 4, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, True, False, True, True, 0, 1024, 160, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', None, '', 'Get Tags', '', '', '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, '<p style="margin-bottom:0.75em">Recommended settings: Use from inpaint tab, inpaint at full res ON, denoise <0.5</p>', 'None', 30, 4, 0, 0, False, 'None', '<br>', 'None', 30, 4, 0, 0, 4, 0.4, True, 32, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "/home/seal/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/home/seal/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/home/seal/stable-diffusion-webui/modules/img2img.py", line 171, in img2img
    processed = process_images(p)
  File "/home/seal/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/home/seal/stable-diffusion-webui/modules/processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/home/seal/stable-diffusion-webui/modules/processing.py", line 1054, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "/home/seal/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 324, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/home/seal/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "/home/seal/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 324, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/home/seal/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/seal/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/home/seal/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/seal/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 119, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "/home/seal/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/seal/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/home/seal/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/home/seal/stable-diffusion-webui/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/home/seal/stable-diffusion-webui/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/home/seal/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/home/seal/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/seal/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/home/seal/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/seal/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 776, in forward
    h = module(h, emb, context)
  File "/home/seal/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/seal/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "/home/seal/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/seal/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 324, in forward
    x = block(x, context=context[i])
  File "/home/seal/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/seal/stable-diffusion-webui/extensions/Hypernetwork-MonkeyPatch-Extension/patches/external_pr/sd_hijack_checkpoint.py", line 5, in BasicTransformerBlock_forward
    return checkpoint(self._forward, x, context)
  File "/home/seal/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/seal/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/seal/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 262, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "/home/seal/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/seal/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 121, in split_cross_attention_forward
    raise RuntimeError(f'Not enough memory, use lower resolution (max approx. {max_res}x{max_res}). '
RuntimeError: Not enough memory, use lower resolution (max approx. 2368x2368). Need: 23.5GB free, Have:18.9GB free
`

**Comment by pkuliyi2015** [comment]
Would you mind paste a screenshot on your tiled diffusion params?

**Comment by sealclubber** [comment]
These werent the exact settings used in the above error log, as I was fiddling with settings to make it work, but were something I screencapped myself for reference. 

![mdsettings](https://user-images.githubusercontent.com/1365445/227430847-0e9e6c81-e342-4e35-a6ce-79f581aea2b3.png)

**Comment by pkuliyi2015** [comment]
Try to tune latent batch size = 2. Should save a half VRAM.

**Comment by sealclubber** [comment]
Running with any batch size (including 1) nets me:

RuntimeError: Not enough memory, use lower resolution (max approx. 2368x2368). Need: 23.5GB free, Have:18.9GB free

Sidenote, I'm not running any memory optimizations on SD, nor am I running xformers.

**Comment by pkuliyi2015** [comment]
Oh that's weird. Let me look further into this.

**Comment by pkuliyi2015** [comment]
Thanks. Please try now and it should be fixed.

**Comment by pkuliyi2015** [comment]
I confirm that all of your problems comes from here. If you succeed, please close the issue.

**Comment by sealclubber** [comment]
It works! Thanks so much for the quick turnaround. 

Funny you should mention the batch issue with img2img, I was about to open a different issue for that but it seems you are already aware. 

Thanks!

**Comment by pkuliyi2015** [comment]
Does the batch_count works now?

**Comment by 49RpK5dY** [comment]
I can confirm that it works for me now. Thank you for fixing this quickly. Should I close the issue now or wait for @sealclubber confirmation?

**Comment by sealclubber** [comment]
I apologize, it was late and I should have been more clear as to what steps I was taking and the actual failure. 

So the problem I'm facing now is actually when doing a batch on a directory in img2img. The first image goes through just fine and spits to the output directory as normal:

```
INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 1 images in a total of 1 batches.
Will process 220 images, creating 1 new images for each.
[Tiled Diffusion] upscaling image with 4x_foolhardy_Remacri...
MultiDiffusion hooked into DPM++ 2M Karras sampler. Tile size: 112x112, Tile batches: 9, Batch size: 2
[Tiled VAE]: input_size: torch.Size([1, 3, 2160, 3840]), tile_size: 2048, padding: 32
[Tiled VAE]: split to 2x2 = 4 tiles. Optimal tile size 1888x1056, original tile size 2048x2048
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 2048 x 1152 image
[Tiled VAE]: Executing Encoder Task Queue: 100%|██████████| 364/364 [00:01<00:00, 294.54it/s]
100%|██████████| 11/11 [01:00<00:00,  5.50s/it]93.025 MB
[Tiled VAE]: input_size: torch.Size([1, 4, 270, 480]), tile_size: 192, padding: 11in2:~$ tail -n 100  nohup.out
[Tiled VAE]: split to 2x3 = 6 tiles. Optimal tile size 160x128, original tile size 192x192
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 192 x 108 image
[Tiled VAE]: Executing Decoder Task Queue: 100%|██████████| 738/738 [00:02<00:00, 298.10it/s]
```

But after going into the second image, it fails with out of memory. Of particular note are the input size params and the encoder task queue, which is exactly ten times the size as in the first image, but all images in this dir are the same resolution or smaller than that first one that works:

```
INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 1 images in a total of 1 batches.
MultiDiffusion Sampling:  81%|████████  | 80/99 [01:24<00:20,  1.06s/it]
[Tiled VAE]: Done in 3.194s, max VRAM alloc 6031.267 MB
[Tiled Diffusion] upscaling image with 4x_foolhardy_Remacri...
MultiDiffusion hooked into DPM++ 2M Karras sampler. Tile size: 112x112, Tile batches: 168, Batch size: 2
[Tiled VAE]: input_size: torch.Size([1, 3, 8640, 15360]), tile_size: 2048, padding: 32
[Tiled VAE]: split to 5x8 = 40 tiles. Optimal tile size 1920x1728, original tile size 2048x2048
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 2048 x 1152 image
[Tiled VAE]: Executing Encoder Task Queue:   3%|▎         | 92/3640 [00:01<00:41, 85.98it/s]Error completing request
```

**Comment by 49RpK5dY** [comment]
It seems that while upscaling works flawlessly the Region Prompt Control stopped working. I'm not sure on which commit it was working last, probably since a couple of days before. I tried changing latent tile size and even fed it a smaller 512x512 image. Also changed the type background/foreground and different samplers. The result is the same.
Here's the log:
`[Tiled Diffusion] upscaling image with 4x_NMKD-Superscale-SP_178000_G...
Mixture of Diffusers hooked into DPM++ SDE Karras sampler. Tile size: 128x128, Tile batches: 1, Batch size: 1
[Tiled VAE]: the input size is tiny and unnecessary to tile.
  0%|                                                                                        | 0/25 [00:00<?, ?it/s]
Error completing requestpling:   0%|                                                         | 0/25 [00:00<?, ?it/s]
Arguments: ('task(shglv6d3wp2jpom)', 0, '', '(deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, (mutated hands and fingers:1.4), disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, (poorly drawn eyes, deformed iris and pupils:1.1), (ugly eyes and mouth, missing teeth:1.2)', ['upscale'], <PIL.Image.Image image mode=RGBA size=512x512 at 0x7F7DB6E5F3D0>, None, None, None, None, None, None, 25, 5, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.4, -1.0, -1.0, 0, 0, 0, False, 768, 512, 0, 1, 96, 0, 'outputs/txt2img', '', '', [], 0, True, 'Mixture of Diffusers', False, True, 1024, 1024, 128, 128, 16, 1, '4x_NMKD-Superscale-SP_178000_G', 2, False, True, False, True, 0.1229166666666666, 0.1708333333333332, 0.4729166666666662, 0.445833333333333, 'cat', '', 'Foreground', 0.2, False, 0.19374999999999998, 0.6249999999999996, 0.11874999999999994, 0.08749999999999986, '', '', 'Foreground', 0.2, False, 0.6874999999999994, 0.620833333333333, 0.13124999999999995, 0.08749999999999994, '', '', 'Foreground', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, True, True, True, True, 0, 1024, 64, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 128, 64, 0.35, 128, 5, True, 0, False, 8, 0, 2, 2048, 2048, 2) {}
Traceback (most recent call last):
  File "/sd/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/sd/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/sd/modules/img2img.py", line 171, in img2img
    processed = process_images(p)
  File "/sd/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/sd/modules/processing.py", line 636, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "/sd/modules/processing.py", line 1054, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "/sd/modules/sd_samplers_kdiffusion.py", line 324, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/sd/modules/sd_samplers_kdiffusion.py", line 227, in launch_sampling
    return func()
  File "/sd/modules/sd_samplers_kdiffusion.py", line 324, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/sd/venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/sd/repositories/k-diffusion/k_diffusion/sampling.py", line 553, in sample_dpmpp_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/modules/sd_samplers_kdiffusion.py", line 125, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": [cond_in[a:b]], "c_concat": [image_cond_in[a:b]]})
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/repositories/k-diffusion/k_diffusion/external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "/sd/repositories/k-diffusion/k_diffusion/external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "/sd/venv/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/sd/extensions/multidiffusion-upscaler-for-automatic1111/methods/mixtureofdiffusers.py", line 157, in apply_model
    x_tile_out = self.custom_apply_model(x_tile, t_in, c_in, bbox_id, bbox, bbox.prompt, bbox.neg_prompt)
  File "/sd/extensions/multidiffusion-upscaler-for-automatic1111/methods/mixtureofdiffusers.py", line 82, in custom_apply_model
    return self.kdiff_custom_forward(x_in, c_in, cond, uncond, bbox_id, bbox,
  File "/sd/extensions/multidiffusion-upscaler-for-automatic1111/methods/abstractdiffusion.py", line 295, in kdiff_custom_forward
    uncond_out = forward_func(
  File "/sd/modules/sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "/sd/modules/sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 776, in forward
    h = module(h, emb, context)
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 324, in forward
    x = block(x, context=context[i])
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 259, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py", line 129, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "/sd/repositories/stable-diffusion-stability-ai/ldm/modules/attention.py", line 263, in _forward
    x = self.attn2(self.norm2(x), context=context) + x
  File "/sd/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/sd/modules/sd_hijack_optimizations.py", line 127, in split_cross_attention_forward
    s1 = einsum('b i d, b j d -> b i j', q[:, i:end], k)
  File "/sd/venv/lib/python3.9/site-packages/torch/functional.py", line 378, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: einsum(): subscript b has size 8 for operand 1 which does not broadcast with previously seen size 0`

**Comment by pkuliyi2015** [comment]
Yes this is a problem. I'm fixing this right now, should be done in at most 2 hours.

**Comment by 49RpK5dY** [comment]
Yes. I just noticed an open issue that seems to be related. Sorry for posting this in the wrong place.

**Comment by pkuliyi2015** [comment]
Try to fix it already. Please have a test.

**Comment by pkuliyi2015** [comment]
Can you just delete the extension and reinstall? It seems that this is a cache error, I guess.

**Comment by 49RpK5dY** [comment]
Did that. Same error. Does it store cache anywhere outside of `extensions/multidiffusion-upscaler-for-automatic1111` folder?

**Comment by pkuliyi2015** [comment]
I successfully reproduce your errors with --medvram. I'm fixing the problem rapidly.

**Comment by 49RpK5dY** [comment]
I see. Glad the problem was found. Just tried without --medvram. It works but only on the selected region, the rest of the picture is just noise. And if I check `Draw tiles as background (SLOW but save VRAM)` I get `HIP out of memory`

**Comment by pkuliyi2015** [comment]
You need to be aware of that, if you don't enable the extension to draw background automatically for you (enable draw tiles as background. That is very slow), **you will need to fill the background area with your own regions.** 

In a nutshell, just draw regions to fill the whole canvas. If your vram is not large enough you can draw multiple regions, using them to fill the canvas. And for the area you want to stress out, you select type as "Foreground".

**Comment by 49RpK5dY** [comment]
Ok. I think I got it. So if all I want is to upscale a picture with multiple subjects in img2img I need to always check Draw tiles as background and put some names in selected regions with foreground type? Which is somewhat similar to what I did a couple of days ago before the big update to regions. This is an extremely useful feature since without it the faces just become a mixture of multiple people.

**Comment by sealclubber** [comment]
So I updated tonight and saw that everything I mentioned is working smoothly and am able to upscale batches of images now with no issues. Wanted to say thanks again and I apologize to @49RpK5dY for hijacking your issue.

Thanks!

**Comment by pkuliyi2015** [comment]
Ah I think you have the same issue. But no worry as in Stable Diffusion WebUI we are all hijacking one another, but in code (Doge):
<img width="232" alt="image" src="https://user-images.githubusercontent.com/59076257/227679596-15e2fbbd-96fc-4a24-8ab9-cbd221d326fd.png">

**Comment by 49RpK5dY** [comment]
Just checked and everything seems to work smoothly. Thanks for the great work.
