### ISSUE TITLE
勾选分块VAE后没有效果(?)

### ISSUE THREAD

**Issue by fandui111** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#59]
显卡：GTX970M（6G） 启动器：秋叶
![image](https://user-images.githubusercontent.com/60561342/227527342-75601358-1dd2-42cd-9041-3f1bc90c080b.png)
报错：
RuntimeError: CUDA out of memory. Tried to allocate 15.64 GiB (GPU 0; 6.00 GiB total capacity; 1.81 GiB already allocated; 2.77 GiB free; 1.85 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

可能是我哪里操作的问题？求大佬解答。

**Comment by pkuliyi2015** [comment]
VAE只是解决编解码器阶段的爆炸，不解决中间阶段。hires该炸还是得炸。
我目前还没有把Tiled Diffusion与t2i hires相兼容，你要生成这么大的highres，只能先生成文生图 不开highres，然后扔进图生图，用我的TiledDiffusion进行放大。
不过，兼容highres只是迟早的事情。

**Comment by boboarts** [comment]
我就是丢到 img2img 用 tiled diffusion 放大，还是照样爆，不知道这个插件解决了什么问题？
![image](https://user-images.githubusercontent.com/1680702/234208644-becfac89-650c-4556-ad2f-991d87399b09.png)

**Comment by fandui111** [comment]
> 我就是丢到 img2img 用 tiled diffusion 放大，还是照样爆，不知道这个插件解决了什么问题？ ![image](https://user-images.githubusercontent.com/1680702/234208644-becfac89-650c-4556-ad2f-991d87399b09.png)

你勾选了配套插件VAE没有，我现在用不爆了，你多试几次，有的时候第一次一定会爆，保持参数不变第二次就不会。

**Comment by boboarts** [comment]
谢谢，我把 vae 的参数都设成最小了，好像可以了。
现在发现这个插件唯一可用的情形就是：
现在  txt2img 生成小图
丢到  img2img 里开 tiled diffusion 放大 同时开 tiled vae

在  txt2img 开 hires tiled vae 也是不可以的。不知道我错过了什么没。
