### ISSUE TITLE
I have updated the extension and now I can't use Hires.fix

### ISSUE THREAD

**Issue by ToniMagi** [pkuliyi2015/multidiffusion-upscaler-for-automatic1111#88]
I had problems because of other extensions disabled, but not deleted from the 'Extensions' folder, the interface to use 'Region Prompt Control' did not appear. Now I have updated the extension and the interface appears, but when using Hires.fix it gives me a CUDA Out of Memory error that I did not get before updating. This is the text from the terminal:

venv "J:\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing requirements for Web UI
Installing sd-dynamic-prompts requirements.txt

Launching Web UI with arguments: --xformers --medvram --opt-split-attention --autolaunch
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: J:\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
Loading booru2prompt settings

======
Error! UniPC sampler support failed to load! Is your WebUI up to date?
(Error: cannot import name 'uni_pc' from 'modules.models.diffusion' (unknown location))
======
[AddNet] Updating model hashes...
100%|█████████████████████████████████████████████████████████████████████████████| 163/163 [00:00<00:00, 72995.04it/s]
[AddNet] Updating model hashes...
100%|█████████████████████████████████████████████████████████████████████████████| 163/163 [00:00<00:00, 61547.67it/s]
Hypernetwork-MonkeyPatch-Extension not found
Loading weights [794da04d40] from J:\stable-diffusion-webui\models\Stable-diffusion\colorful_v21.ckpt
Creating model from config: J:\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(144): angry512, anime-bckgrnd, archer-style, bad-artist-anime, bad-artist, bad-hands-5, bad-image-v2-39000, bad_prompt, bad_prompt_version2, bad_quality, barbosa_style, blowjobpose, bottomless, brshields, c4m3r0nd14z, centerfold512, charlizetheron_ti, charturnerv2, chlmtz2, corneo_anal, corneo_black_cat_dva, corneo_brigitte, corneo_tracer, defiance512, dollienobodysd15, dr-strange, dualipa, EasyNegative, emb-babs, emmastone, emmsto, fenn_mei, flower_style, frank-frazetta, grin512, happy512, hcarolin, hoppagames, isabela, JeBeFlash2, jencon90s, jflw, K3LLY8R00K2, kc16-4000-sd1-5, koh_daisyridley, koh_emiliaclarke, kristen, landscape_style, laugh512, lindsaylohan, maievska, missmiafit, moebius, morb4cc4r1n, Neringa_T_V10-600, nervous512, ng_deepnegative_v1_75t, nixeu, nixeu_basic, nixeu_basic2, nixeu_extra, nixeu_soft, nixeu_white, olfn, pffpffpff, pinup512, pugh-subject, realcumAI, RFKTR_fshnsta, RFKTR_plastic, ruan-jia, sad512, sakimi-style, samdoesarts, shock512, smile512, space_style-7500, splash_style, Style-BladeRunner2049-8v, style-bridal, style-empire-neg, style-empire, Style-Moana-neg, Style-Moana, Style-NebMagic-neg, Style-NebMagic, style-paintmagic, style-rustmagic-neg, style-rustmagic, style-sylvamagic, tarab, tarot512, tcircles, thelab-ada, ulzzang-6500-v1.1, ulzzang-6500, vile_prompt3, was-ja, was-pp, was-vb, wlop-style, xmsorn, 3mmar0b3rts, 3nid_14, aliciasilverstone, ann3hathawa72, antonialastnamesd15, brecbella-700-1100, brielastnamdsd15, bs_purpalpaca, c0b13smu1d3rs2, c0urt400, caoimhelastnamesd15, cecelia, dak0tafann1ng3, eliselastnamesd15, EmWat69, emwatz, Florenc3, GITSEllie, imogend, j0rd7nj0n3s, jcon-subject, JeAni69, katd3nn1ngs2, kath3r1n3langf0rd2, koh_doutzenkroes, koh_lanarhoades, lucy_kushinadaV2, lyncarv3, M11anaVa7ntrub2, maisiewilliams, mar1shara7, margot-robbie-subject, milkun, natalie portman, s0f1av3rgara, scarjo-subject, sd15-charlize-theron, stana-t2, taylorswift-subject, w3day_15-light, Z3NNND4Y42222, atompunkstylesd15
Model loaded in 2.3s (load weights from disk: 0.8s, create model: 0.4s, apply weights to model: 0.5s, apply half(): 0.4s, load textual inversion embeddings: 0.1s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:27<00:00,  1.39s/it]
[Tiled VAE]: input_size: torch.Size([1, 4, 96, 54]), tile_size: 64, padding: 11        | 20/40 [00:43<00:26,  1.32s/it]
[Tiled VAE]: split to 2x1 = 2 tiles. Optimal tile size 32x64, original tile size 64x64
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 36 x 64 image
[Tiled VAE]: Executing Decoder Task Queue: 100%|████████████████████████████████████| 246/246 [00:01<00:00, 186.86it/s]
[Tiled VAE]: Done in 2.188s, max VRAM alloc 614.456 MB
[Tiled VAE]: input_size: torch.Size([1, 3, 1920, 1080]), tile_size: 960, padding: 32
[Tiled VAE]: split to 2x2 = 4 tiles. Optimal tile size 512x928, original tile size 960x960
[Tiled VAE]: Fast mode enabled, estimating group norm parameters on 540 x 960 image
[Tiled VAE]: Executing Encoder Task Queue: 100%|█████████████████████████████████████| 364/364 [00:03<00:00, 97.07it/s]
[Tiled VAE]: Done in 4.968s, max VRAM alloc 764.836 MB
  0%|                                                                                           | 0/20 [00:07<?, ?it/s]
Error completing request
Arguments: ('task(gse0o1wfzggsw7x)', '(full body view:1.1), photoshoot Evangeline Lilly, (black traslucent camisole:1.3), sex time, wishful, beautiful detailed face, large blue eyes, perfect hourglass figure, mucular thighs, black strappy heeled sandals, perfect hairy pussy, perfect perky tits, (front view:1.2), (wavy disheveled hairstyle:1.2), highly detailed, studio warm torches lighting, burning torches on the walls, detailed dungeon background, warm bloom, motion, realism, high-quality rendering, stunning art, high quality, film grain, Fujifilm XT3, dreamy <lora:epiNoiseoffset_v2:1>', 'bad anatomy, low-res, (watermarks:1.2), username, paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), monochrome, grayscale, (easynegative:1.1),  bad anatomy, low-res, poorly drawn face, disfigured hands, poorly drawn eyebrows, bad body perspective, animal tail, anime, nipples, pussy, wrong anatomy, poorly drawn legs, wrong perspective legs, poorly drawn hands, (bad-hands-5:1.8), wrong hand, yellow light, canvas frame, cartoon, 3d, ((disfigured)), ((bad art)), ((deformed)),((extra limbs)),((close up)),((b&w)), wierd colors, blurry, (((duplicate))), ((morbid)), ((mutilated)), [out of frame], signature, watermarks', [], 20, 0, False, False, 1, 1, 3, 367770823.0, -1.0, 0, 0, 0, False, 768, 432, True, 0.15, 2.5, 'lollypop', 0, 0, 0, [], 0, False, 'MultiDiffusion', False, 10, 10, 1, 64, False, True, 1024, 1024, 96, 96, 48, 1, 'None', 2, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, True, True, True, True, 0, 960, 64, True, False, 1, False, False, False, 1.1, 1.5, 100, 0.7, False, False, True, False, False, 0, 'Gustavosta/MagicPrompt-Stable-Diffusion', '', False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, None, 'Refresh models', <scripts.external_code.ControlNetUnit object at 0x00000294B808C580>, '', '', False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, 50) {}
Traceback (most recent call last):
  File "J:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "J:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "J:\stable-diffusion-webui\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "J:\stable-diffusion-webui\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "J:\stable-diffusion-webui\modules\processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "J:\stable-diffusion-webui\modules\processing.py", line 902, in sample
    samples = self.sampler.sample_img2img(self, samples, noise, conditioning, unconditional_conditioning, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
  File "J:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 322, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "J:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "J:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 322, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "J:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 145, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "J:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 123, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": [cond_in[a:b]], "c_concat": [image_cond_in[a:b]]})
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "J:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "J:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "J:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "J:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "J:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "J:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1329, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "J:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 781, in forward
    h = module(h, emb, context)
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "J:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "J:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 324, in forward
    x = block(x, context=context[i])
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "J:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 259, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "J:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "J:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 129, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "J:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 264, in _forward
    x = self.ff(self.norm3(x)) + x
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "J:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 73, in forward
    return self.net(x)
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "J:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 52, in forward
    x, gate = self.proj(x).chunk(2, dim=-1)
  File "J:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "J:\stable-diffusion-webui\extensions-builtin\Lora\lora.py", line 178, in lora_Linear_forward
    return lora_forward(self, input, torch.nn.Linear_forward_before_lora(self, input))
  File "J:\stable-diffusion-webui\extensions\a1111-sd-webui-locon\scripts\main.py", line 494, in lora_forward
    res = res + module.inference(x) * scale
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 160.00 MiB (GPU 0; 3.00 GiB total capacity; 2.27 GiB already allocated; 0 bytes free; 2.45 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by pkuliyi2015** [comment]
Weird. with the latest version I optimized some VRAM usage; But may not be very effective. You may have a test.

**Comment by ToniMagi** [comment]
Thanks. I think is a LORA problem. Only show CUDA error when in the prompt there is some LORA. But last night I read on Reddit that the 'Multiple hypernetworks' extension was giving errors with the use of LORAs. I have disabled it and deleted the extension folder in the Auto1111 'Extensions' folder and now it works fine with LORAs again. Thank you for your attention and response! I adore your extension, it has given me back an immense field of possibilities that with my 3Gbs of VRAM were unthinkable before!
